@echo off
cd /d C:\ai\pi-agent-desktop\apps\desktop
echo [Pi Agent] Building...
call pnpm run build >NUL 2>NUL
echo [Pi Agent] Starting...
start "" "C:\ai\pi-agent-desktop\apps\desktop\node_modules\.bin\electron.CMD" .
